import { Activity, Flame, Leaf, RefreshCw, ShieldCheck, Sparkles, Wind } from 'lucide-react'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import type { Dosha } from '../types'
import { DashboardSidebar } from './DashboardSidebar'
import { FooterLogo } from './FooterLogo'

type Daily = { date: string; total: number; doshas: Record<Dosha, number> }
type Profile = { dosha: Dosha; count: number; percentage: number; consentRate: number; averageScore: number }
type Analysis = { total: number; dominantDosha: Dosha | null; balancedCount: number; balancedRate: number; marketingConsent: { count: number; rate: number }; lastSeven: number; growthRate: number | null; primary: Profile[]; scoreAverages: Record<Dosha, number>; combinations: { primary: Dosha; secondary: Dosha; count: number }[]; registrationsByDay: Daily[] }
const labels: Record<Dosha, string> = { vata: 'Vata', pitta: 'Pitta', kapha: 'Kapha' }
const icons: Record<Dosha, typeof Wind> = { vata: Wind, pitta: Flame, kapha: Leaf }

function requestAnalysis() { return fetch('/api/doshas').then((response) => { if (response.status === 401) window.location.assign('/login'); if (!response.ok) throw new Error('Falha ao carregar análise'); return response.json() as Promise<Analysis> }) }
function emptyAnalysis(): Analysis { return { total: 0, dominantDosha: null, balancedCount: 0, balancedRate: 0, marketingConsent: { count: 0, rate: 0 }, lastSeven: 0, growthRate: null, primary: (['vata', 'pitta', 'kapha'] as Dosha[]).map((dosha) => ({ dosha, count: 0, percentage: 0, consentRate: 0, averageScore: 0 })), scoreAverages: { vata: 0, pitta: 0, kapha: 0 }, combinations: [], registrationsByDay: [] } }
function formatDate(date: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit' }).format(new Date(`${date}T12:00:00`)) }

export function DoshasScreen() {
  const [analysis, setAnalysis] = useState<Analysis | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => { setLoading(true); setError(''); void requestAnalysis().then(setAnalysis).catch(() => setError('Não foi possível carregar a análise agora.')).finally(() => setLoading(false)) }
  useEffect(() => { void requestAnalysis().then(setAnalysis).catch(() => setError('Não foi possível carregar a análise agora.')).finally(() => setLoading(false)) }, [])
  const data = analysis ?? emptyAnalysis(); const maxCount = Math.max(...data.primary.map((item) => item.count), 1); const maxScore = Math.max(...Object.values(data.scoreAverages), 1); const trend = useMemo(() => data.registrationsByDay.slice(-14), [data.registrationsByDay]); const maxTrend = Math.max(...trend.map((day) => day.total), 1)
  return <div className="reference-dashboard doshas-dashboard"><DashboardSidebar active="doshas" /><main className="reference-main doshas-main">
    <header className="doshas-header"><div><h1>Análise de doshas</h1><p>Leia os padrões reais dos cadastros para orientar a comunicação do Meu Ritmo.</p></div><button className="registrations-refresh" type="button" onClick={load} disabled={loading}><RefreshCw aria-hidden="true" size={18} className={loading ? 'is-spinning' : ''} /> Atualizar</button></header>
    {error ? <p className="reference-error" role="alert">{error}</p> : <>
      <section className="reference-metrics doshas-metrics" aria-label="Resumo da análise"><Metric icon={<Activity />} label="Leads analisados" value={data.total} detail="Resultados salvos" /><Metric icon={data.dominantDosha ? <Icon dosha={data.dominantDosha} /> : <Leaf />} label="Perfil dominante" value={data.dominantDosha ? labels[data.dominantDosha] : '—'} detail="Maior incidência" accent /><Metric icon={<ShieldCheck />} label="Com consentimento" value={`${data.marketingConsent.rate}%`} detail={`${data.marketingConsent.count} contatos autorizados`} /><Metric icon={<Sparkles />} label="Equilíbrio" value={`${data.balancedRate}%`} detail={`${data.balancedCount} perfis equilibrados`} /></section>
      <section className="reference-card doshas-distribution"><Heading title="Distribuição dos perfis" description="Dosha predominante informado em cada resultado." detail={`${data.total} leads`} /><div className="doshas-profile-list">{data.primary.map((profile) => <ProfileRow key={profile.dosha} profile={profile} maxCount={maxCount} />)}</div></section>
      <section className="doshas-grid"><section className="reference-card doshas-score-card"><Heading title="Intensidade média" description="Média de respostas por dosha em 15 perguntas." /> <div className="doshas-score-list">{(['vata', 'pitta', 'kapha'] as Dosha[]).map((dosha) => <div className="doshas-score-row" key={dosha}><span>{labels[dosha]}</span><div><i className={dosha} style={{ width: `${(data.scoreAverages[dosha] / maxScore) * 100}%` }} /></div><strong>{data.scoreAverages[dosha].toLocaleString('pt-BR', { maximumFractionDigits: 1 })}</strong></div>)}</div></section><section className="reference-card doshas-combination-card"><Heading title="Combinações recorrentes" description="Perfis que aparecem juntos e merecem mensagens específicas." />{data.combinations.length ? <ol className="doshas-combinations">{data.combinations.map((item) => <li key={`${item.primary}-${item.secondary}`}><span><Icon dosha={item.primary} />{labels[item.primary]} + {labels[item.secondary]}</span><strong>{item.count} leads</strong></li>)}</ol> : <p className="reference-empty">As combinações aparecerão quando houver resultados mistos.</p>}</section></section>
      <section className="doshas-grid"><section className="reference-card doshas-consent-card"><Heading title="Potencial de comunicação" description="Consentimento de marketing por dosha predominante." /><div className="doshas-consent-list">{data.primary.map((profile) => <div key={profile.dosha}><span>{labels[profile.dosha]}</span><div><i className={profile.dosha} style={{ width: `${profile.consentRate}%` }} /></div><strong>{profile.consentRate}%</strong></div>)}</div></section><section className="reference-card doshas-trend-card"><Heading title="Ritmo de entradas" description={`Últimos 14 dias: ${data.lastSeven} novos leads na semana.`} detail={data.growthRate === null ? 'Sem base anterior' : `${data.growthRate > 0 ? '+' : ''}${data.growthRate}% vs. semana anterior`} /><div className="doshas-trend" aria-label="Cadastros por dia nos últimos quatorze dias">{trend.map((day) => <div key={day.date}><span style={{ height: `${Math.max(4, (day.total / maxTrend) * 100)}%` }} title={`${formatDate(day.date)}: ${day.total} cadastros`} /><small>{formatDate(day.date)}</small></div>)}</div></section></section>
    </>}<FooterLogo className="reference-footer" />
  </main></div>
}
function Icon({ dosha }: { dosha: Dosha }) { const IconComponent = icons[dosha]; return <IconComponent aria-hidden="true" size={20} strokeWidth={1.5} /> }
function Metric({ icon, label, value, detail, accent = false }: { icon: ReactNode; label: string; value: string | number; detail: string; accent?: boolean }) { return <article className={`reference-metric ${accent ? 'is-accent' : ''}`}><span className="reference-metric-icon">{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }
function Heading({ title, description, detail }: { title: string; description: string; detail?: string }) { return <div className="doshas-card-heading"><div><h2>{title}</h2><p>{description}</p></div>{detail && <small>{detail}</small>}</div> }
function ProfileRow({ profile, maxCount }: { profile: Profile; maxCount: number }) { return <div className="doshas-profile-row"><span className={`doshas-profile-icon ${profile.dosha}`}><Icon dosha={profile.dosha} /></span><div><strong>{labels[profile.dosha]}</strong><small>{profile.count} leads · {profile.consentRate}% com consentimento</small></div><div className="doshas-profile-track"><i className={profile.dosha} style={{ width: `${(profile.count / maxCount) * 100}%` }} /></div><b>{profile.percentage}%</b></div> }
