import type { IncomingMessage, ServerResponse } from 'node:http'
import { hashActivationToken } from './_lib/member-activation.js'
import { clearMemberSession, email, hashMemberPassword, memberSession, setMemberSession, verifyMemberPassword } from './_lib/member-auth.js'

const send = (res: ServerResponse, status: number, body: Record<string, unknown>) => { res.statusCode = status; res.setHeader('Cache-Control', 'no-store'); res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.end(JSON.stringify(body)) }
const db = () => { const url = process.env.SUPABASE_URL?.replace(/\/$/, ''); const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url, key } : null }
async function body(req: IncomingMessage) { let value = ''; for await (const chunk of req) { value += chunk; if (value.length > 4096) throw new Error('large') }; return JSON.parse(value) as { action?: string; name?: string; email?: string; password?: string; activationToken?: string } }
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const connection = db(); if (!connection) return send(res, 503, { error: 'Serviço indisponível.' }); const headers = { apikey: connection.key, Authorization: `Bearer ${connection.key}`, 'Content-Type': 'application/json' }
  if (req.method === 'GET') { const session = memberSession(req); return send(res, session ? 200 : 401, { authenticated: Boolean(session), member: session ? { email: session.email } : null }) }
  if (req.method !== 'POST') { res.setHeader('Allow', 'GET, POST'); return send(res, 405, { error: 'Método não permitido.' }) }
  try { const data = await body(req); if (data.action === 'logout') { clearMemberSession(res); return send(res, 200, { ok: true }) }; const password = typeof data.password === 'string' ? data.password : ''; if (data.action === 'activate') { const token = typeof data.activationToken === 'string' ? data.activationToken : ''; if (token.length < 40 || token.length > 128 || password.length < 10 || password.length > 256) return send(res, 422, { error: 'Link ou senha inválidos.' }); const tokenHash = hashActivationToken(token); const lookup = await fetch(`${connection.url}/rest/v1/member_accounts?activation_token_hash=eq.${encodeURIComponent(tokenHash)}&select=id,email,activation_expires_at&limit=1`, { headers }); if (!lookup.ok) throw new Error('activation-read'); const account = (await lookup.json() as { id: string; email: string; activation_expires_at: string | null }[])[0]; if (!account || !account.activation_expires_at || new Date(account.activation_expires_at).getTime() <= Date.now()) return send(res, 410, { error: 'Este link expirou. Solicite um novo acesso.' }); const update = await fetch(`${connection.url}/rest/v1/member_accounts?id=eq.${encodeURIComponent(account.id)}&activation_token_hash=eq.${encodeURIComponent(tokenHash)}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json', Prefer: 'return=representation' }, body: JSON.stringify({ password_hash: hashMemberPassword(password), activation_token_hash: null, activation_expires_at: null, activated_at: new Date().toISOString(), updated_at: new Date().toISOString(), status: 'approved' }) }); if (!update.ok || !(await update.json() as { id: string }[])[0]) return send(res, 410, { error: 'Este link não está mais disponível.' }); setMemberSession(res, account); return send(res, 200, { ok: true }) }; const accountEmail = typeof data.email === 'string' ? email(data.email) : null; if (!accountEmail || password.length < 10 || password.length > 256) return send(res, 422, { error: 'Informe e-mail válido e senha de ao menos 10 caracteres.' })
    if (data.action === 'register') { const name = typeof data.name === 'string' ? data.name.trim() : ''; if (name.length < 2 || name.length > 100) return send(res, 422, { error: 'Informe seu nome completo.' }); const result = await fetch(`${connection.url}/rest/v1/member_accounts`, { method: 'POST', headers: { ...headers, Prefer: 'return=minimal' }, body: JSON.stringify({ full_name: name, email: accountEmail, password_hash: hashMemberPassword(password) }) }); if (result.status === 409) return send(res, 409, { error: 'Este e-mail já possui cadastro.' }); return result.ok ? send(res, 201, { ok: true }) : send(res, 502, { error: 'Não foi possível concluir o cadastro.' }) }
    if (data.action === 'login') { const result = await fetch(`${connection.url}/rest/v1/member_accounts?email=eq.${encodeURIComponent(accountEmail)}&select=id,email,password_hash,status&limit=1`, { headers }); if (!result.ok) throw new Error('read'); const account = (await result.json() as { id: string; email: string; password_hash: string; status: string }[])[0]; if (!account || !verifyMemberPassword(password, account.password_hash)) return send(res, 401, { error: 'E-mail ou senha inválidos.' }); if (account.status !== 'approved') return send(res, 403, { error: account.status === 'pending' ? 'Seu cadastro está aguardando aprovação.' : 'Seu acesso não está disponível.' }); setMemberSession(res, account); return send(res, 200, { ok: true }) }
    return send(res, 422, { error: 'Ação inválida.' })
  } catch { return send(res, 400, { error: 'Não foi possível processar sua solicitação.' }) }
}
